//! SKILL.md frontmatter parsing + generated-artifact construction.
//!
//! Both agents use the open Agent-Skills format: a `---`-fenced YAML block
//! (`name` + `description` the only universally-read keys) followed by a
//! Markdown body. The body is copied verbatim; only the frontmatter is
//! translated. Because the mirror is *generated*, we serialize a fresh,
//! canonical frontmatter rather than preserving the source's byte formatting —
//! this keeps output deterministic (idempotent) run to run.

use crate::agent::Agent;
use serde_yaml::{Mapping, Value};

/// The change-detection + loop-safety marker read from `metadata`.
pub struct Marker {
    pub ported_by: String,
    pub source_agent: String,
    pub source_name: String,
    pub render_hash: String,
    pub porter_version: String,
}

/// Typed inputs for the generated mirror frontmatter. Keeping these together
/// makes the render plan and writer share one output contract.
pub struct MirrorFrontmatter<'a> {
    pub mirror_name: &'a str,
    pub description: &'a str,
    pub target: Agent,
    pub implicit_allowed: bool,
    pub allowed_tools: Option<&'a Value>,
    pub source_agent: Agent,
    pub source_name: &'a str,
    pub render_hash: &'a str,
}

/// Split raw SKILL.md text into `(frontmatter_yaml, body)`. Returns `None` when
/// there is no leading `---` fence or no closing `\n---\n` — callers treat that
/// as "no usable frontmatter" and skip the skill.
pub fn split(text: &str) -> Option<(&str, &str)> {
    let rest = text.strip_prefix("---\n")?;
    let end = rest.find("\n---\n")?;
    Some((&rest[..end], &rest[end + "\n---\n".len()..]))
}

/// Parse a frontmatter block into a YAML mapping. An empty/`null` block yields
/// an empty mapping; a non-mapping (e.g. a bare list) is an error.
pub fn parse_mapping(fm: &str) -> crate::Result<Mapping> {
    match serde_yaml::from_str::<Value>(fm)? {
        Value::Mapping(m) => Ok(m),
        Value::Null => Ok(Mapping::new()),
        _ => Err("SKILL.md frontmatter is not a YAML mapping".into()),
    }
}

fn key(k: &str) -> Value {
    Value::String(k.to_string())
}

pub fn get_str(m: &Mapping, k: &str) -> Option<String> {
    m.get(k).and_then(|v| v.as_str()).map(str::to_string)
}

pub fn get_bool(m: &Mapping, k: &str) -> Option<bool> {
    m.get(k).and_then(Value::as_bool)
}

fn metadata(m: &Mapping) -> Option<&Mapping> {
    m.get("metadata").and_then(Value::as_mapping)
}

/// Read the porter marker from a parsed frontmatter, if present.
pub fn marker(m: &Mapping) -> Option<Marker> {
    let meta = metadata(m)?;
    let ported_by = get_str(meta, "ported_by")?;
    Some(Marker {
        ported_by,
        source_agent: get_str(meta, "source_agent").unwrap_or_default(),
        source_name: get_str(meta, "source_name").unwrap_or_default(),
        render_hash: get_str(meta, "render_hash").unwrap_or_default(),
        porter_version: get_str(meta, "porter_version").unwrap_or_default(),
    })
}

/// True when this frontmatter was generated by *this* porter — the signal the
/// enumerator uses to skip mirrors and the writer uses to know a target is safe
/// to overwrite.
pub fn is_ported(m: &Mapping) -> bool {
    marker(m).is_some_and(|mk| mk.ported_by == crate::PORTER_ID)
}

/// Render a frontmatter mapping + body back into SKILL.md text.
pub fn render(fm: &Mapping, body: &str) -> crate::Result<String> {
    let yaml = serde_yaml::to_string(fm)?; // trailing newline included
    Ok(format!("---\n{yaml}---\n{body}"))
}

/// Build the generated mirror's frontmatter.
///
/// `implicit_allowed` is the normalized cross-agent invocation policy (may the
/// model auto-invoke this skill?). For a Claude target it becomes
/// `disable-model-invocation` (only emitted when auto-invocation is *off*, to
/// keep the common case clean); for a Codex target it is carried in
/// `agents/openai.yaml` instead (see [`build_openai_yaml`]).
pub fn build_mirror_frontmatter(input: &MirrorFrontmatter<'_>) -> Mapping {
    let mut fm = Mapping::new();
    fm.insert(key("name"), Value::String(input.mirror_name.to_string()));
    fm.insert(
        key("description"),
        Value::String(input.description.to_string()),
    );

    if input.target == Agent::Claude {
        if let Some(tools) = input.allowed_tools {
            fm.insert(key("allowed-tools"), tools.clone());
        }
        if !input.implicit_allowed {
            fm.insert(key("disable-model-invocation"), Value::Bool(true));
        }
    }

    let mut meta = Mapping::new();
    meta.insert(
        key("ported_by"),
        Value::String(crate::PORTER_ID.to_string()),
    );
    meta.insert(
        key("porter_version"),
        Value::String(crate::PORTER_VERSION.to_string()),
    );
    meta.insert(
        key("source_agent"),
        Value::String(input.source_agent.as_str().to_string()),
    );
    meta.insert(
        key("source_name"),
        Value::String(input.source_name.to_string()),
    );
    meta.insert(
        key("render_hash"),
        Value::String(input.render_hash.to_string()),
    );
    fm.insert(key("metadata"), Value::Mapping(meta));

    fm
}

/// Build the optional Codex `agents/openai.yaml` for a ported skill whose
/// invocation policy is non-default. Ordinary skills omit this file entirely
/// to keep large skill-corpus reloads lean.
pub fn build_openai_yaml(display_name: &str, description: &str) -> crate::Result<String> {
    let mut interface = Mapping::new();
    interface.insert(key("display_name"), Value::String(display_name.to_string()));
    interface.insert(
        key("short_description"),
        Value::String(truncate(description, 120)),
    );

    let mut policy = Mapping::new();
    policy.insert(key("allow_implicit_invocation"), Value::Bool(false));

    let mut root = Mapping::new();
    root.insert(key("interface"), Value::Mapping(interface));
    root.insert(key("policy"), Value::Mapping(policy));

    Ok(serde_yaml::to_string(&root)?)
}

fn truncate(s: &str, max: usize) -> String {
    let s = s.trim();
    if s.chars().count() <= max {
        return s.to_string();
    }
    let mut out: String = s.chars().take(max.saturating_sub(1)).collect();
    // Trim back to the last whitespace for a cleaner cut, if one is nearby.
    if let Some(idx) = out.rfind(char::is_whitespace) {
        if idx >= max / 2 {
            out.truncate(idx);
        }
    }
    format!("{}…", out.trim_end())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn split_extracts_frontmatter_and_body() {
        let (fm, body) = split("---\nname: x\ndescription: y\n---\nhello\n").unwrap();
        assert_eq!(fm, "name: x\ndescription: y");
        assert_eq!(body, "hello\n");
    }

    #[test]
    fn split_rejects_missing_fences() {
        assert!(split("# just markdown\n").is_none());
        assert!(split("---\nunterminated\n").is_none());
    }

    #[test]
    fn marker_round_trips() {
        let fm = build_mirror_frontmatter(&MirrorFrontmatter {
            mirror_name: "codex-foo",
            description: "desc",
            target: Agent::Claude,
            implicit_allowed: true,
            allowed_tools: None,
            source_agent: Agent::Codex,
            source_name: "foo",
            render_hash: "render123",
        });
        assert!(is_ported(&fm));
        let mk = marker(&fm).unwrap();
        assert_eq!(mk.source_agent, "codex");
        assert_eq!(mk.source_name, "foo");
        assert_eq!(mk.render_hash, "render123");
    }

    #[test]
    fn claude_target_emits_disable_when_implicit_off() {
        let fm = build_mirror_frontmatter(&MirrorFrontmatter {
            mirror_name: "codex-foo",
            description: "d",
            target: Agent::Claude,
            implicit_allowed: false,
            allowed_tools: None,
            source_agent: Agent::Codex,
            source_name: "foo",
            render_hash: "r",
        });
        assert_eq!(get_bool(&fm, "disable-model-invocation"), Some(true));
    }

    #[test]
    fn codex_target_omits_disable_key() {
        let fm = build_mirror_frontmatter(&MirrorFrontmatter {
            mirror_name: "claude-foo",
            description: "d",
            target: Agent::Codex,
            implicit_allowed: false,
            allowed_tools: None,
            source_agent: Agent::Claude,
            source_name: "foo",
            render_hash: "r",
        });
        assert_eq!(get_bool(&fm, "disable-model-invocation"), None);
    }

    #[test]
    fn openai_yaml_reflects_policy() {
        let y = build_openai_yaml("claude-foo", "d").unwrap();
        assert!(y.contains("allow_implicit_invocation: false"));
        assert!(y.contains("display_name: claude-foo"));
    }

    #[test]
    fn not_ported_for_user_authored_skill() {
        let m = parse_mapping("name: mine\ndescription: hand written").unwrap();
        assert!(!is_ported(&m));
    }
}
